apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - bei
    environmentGitOwner: bernd-eilers
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: bei
    repository: jx3-kubernetes
  - key: staging
  - key: itest
  - key: prodtest
  - key: pat
  - key: production
  ingress:
    domain: "service.fms.local"
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  pipelineUser:
    username: bei
  repository: nexus
  secretStorage: local
  vault: {}
  webhook: lighthouse
